### ISSUE TITLE
MVP Design (Final Checklist)

### ISSUE THREAD

**Issue by Tmunayyer** [Tmunayyer/craigwatch#36]
I closed the old and am opening a new issue to track the final things to tidy up the application to reach MVP status. I'll track the remaining tasks by component.

1. Search Form
- [x] Styling still feels a bit strange here. It needs to change.
- [x] Input field validations.
- [X] A Tooltip with some information about whats going on. (decided to use placeholders instead of a tooltip)
- [x] Unit tests.

finished in PR #37 

2. Search List
- [x] Empty state/error state.
- [x] There should be some indication of how many listings it has found. (going to add this as a separate issue)
- [x] Unit tests.

finished in PR #38 

3. Result Summary
- [x] Styling in a similar vein as the form.
- [x] Empty state/error state.
- [x] Add metrics in some form. (going to add this as a separate issue)
- [x] Unit tests.

finished in #40 

4. Result List
- [x] Empty state/error state.
- [x] Pagination for results so there aren't 100s of items on-page. (add this as a separate issue)
- [x] Unit tests.
