### ISSUE TITLE
general ui update checklist

### ISSUE THREAD

**Issue by Tmunayyer** [Tmunayyer/craigwatch#65]
**The problem:**
A few things I notice here and there that should be updated. Collect an ongoing list to do it all at once.

**Proposed solution:**
- [x] activity chart title should be lower case
- [x] result summary updates, add timezone
- [x] the activity chart is backwards
- [x] show more button needs to be centered
- [x] a result page should be two columns
- [x] narrow list items break dates under header
